### ISSUE TITLE
Error Pasting in V11.302

### ISSUE THREAD

**Issue by derSebastian** [saif-ellafi/foundryvtt-clipboard-image#3]
Error Pasting in V11.302

Error in console:

Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'getLocalPosition')
[Detected 1 package: clipboard-image]
    at _pasteBlob (clipboard-image.js:61:66)
    at clipboard-image.js:137:19

_pasteBlob | @ | clipboard-image.js:61

  | (anonymous) | @ clipboard-image.js:137
  | Promise.then (async) |   |  
  | (anonymous) | @ clipboard-image.js:135
  | Promise.then (async) |   |  
  | (anonymous) | @ clipboard-image.js:134
  | Promise.then (async) |   |  
  | onDown | @ clipboard-image.js:132
  | _executeKeybind | @ foundry.js:2500
  | _processKeyboardContext | @ foundry.js:2541
  | _handleKeyboardEvent | @ foundry.js:2599
  | (anonymous) | @ foundry.js:2225

**Comment by saif-ellafi** [comment]
Hi @derSebastian - Upgaded for Foundry V11 
Can you check now?
Thanks

**Comment by derSebastian** [comment]
@saif-ellafi Can confirm it works!  On Foundry 11 v302 -- nice work! Appreciate it.

Q: is there a reason copy/paste wont work from desktop (OSX)?

**Comment by saif-ellafi** [comment]
@derSebastian - did it work, ever before?
Sorry I don't have a macbook. Tried Google Chrome browser?

**Comment by derSebastian** [comment]
Good question. I don't recall, should have kept a record. But I can drag an image into Chrome/chromium browser and then drag it into Foundry. Or drag it into the tile browser view and from there onto the canvas. I can't copy/paste from Desktop (OSX 13.4) nor drag and drop from the same. Just to keep a note now.

**Comment by saif-ellafi** [comment]
Thanks - please open a separate issue in case it affect others or if others can confirm
