### ISSUE TITLE
Can break scene with Tokenizer module

### ISSUE THREAD

**Issue by cass-f20** [saif-ellafi/foundryvtt-clipboard-image#5]
If you use the Tokenizer feature of pasting an image while Clipboard module is active it will paste the image on the map too and for me on pf2e Forge consistently breaks the scene.

**Comment by saif-ellafi** [comment]
Yeah it would be great to fix this. I noticed it too. Will keep it in mind

**Comment by saif-ellafi** [comment]
Fixed in next release!
